### PR TITLE
fix #26 - Adding fast mode support to field

### LINKED ISSUE #26: FastField Support
I'm really happy how this project has evolved, I feel like it's at a really good spot right now. 👍

https://jaredpalmer.com/formik/docs/api/fastfield
This is just a feature request for the future of this package. Could be really useful for some ( I might even try them out for optimization ) 

I believe the FastField uses the same API as Field so it shouldn't be too crazy to implement.
Not sure if we should make new components for each (but using FastField) or make some kind of switch in the component itself.
Either way, I'd hope it maintains our clean coding standard so far.

### PR DESCRIPTION
**Pull request by gabrielberlanda**
refs #26

### CODE REVIEW

**Comment by jannikbuschke** [comment]
mh, what about naming the prop just 'fast'? its a tiny bit simpler and less keywords to type. Usually I prefer longer descriptive names, however we have a really small api-surface, and it would be just a little bit more minimalistic and elegant. Opinions?
I dont think we are clashing with any ant design props in either way.

**Comment by gabrielberlanda** [comment]
Seems good to me, I will change it now.

**Comment by jannikbuschke** [comment]
nice!

**Comment by jannikbuschke** [comment]
@allcontributors add @gabrielberlanda  for code

**Pull request merged**
