### PR TITLE
Fix Checkbox.Group & Radio.Group for Ant Design 5

### PR DESCRIPTION
**Pull request by Vincz**
Like the previous fix, this one does the fix for `Checkbox.Group` and `Radio.Group`.  
I checked the other components and they seem fine.

### CODE REVIEW

**Comment by Vincz** [comment]
Hi @jannikbuschke :-)
Do you mind to compile and publish a new beta version for this please?
Thanks!

**Comment by Vincz** [comment]
ping @jannikbuschke 😸

**Comment by Vincz** [comment]
Hey @jannikbuschke! 
So sorry to insist but would you mind to publish this (I really think it's the last thing preveting the compatibility with ant5).
Thanks!

**Comment by jannikbuschke** [comment]
Sorry for the unresponsiveness, Im quite busy with other stuff...

**Pull request merged**
