### PR TITLE
Track/1.0

### PR DESCRIPTION
**Pull request by jannikbuschke**
A PR to track the remaining work for a 1.0 release

- [ ] Find solution/recommendation whether to use `<form>` and native button type attributes
- [ ] Add Cascader
- [ ] Add TreeSelect
- [ ] Add Mention
- [ ] Create a pre-release

### CODE REVIEW

**Comment by joshsmith** [comment]
As part of 1.0 are you planning on having labels work? Currently, I believe that setting `name` is causing labels to be broken and not know what the `for` should be.

**Comment by jannikbuschke** [comment]
Can you elaborate a bit which labels you mean exactly?

**Comment by joshsmith** [comment]
> Can you elaborate a bit which labels you mean exactly?

Sure, here's a forked example of your CodeSandbox: https://codesandbox.io/s/y257p4l8z9

The `label` element for `[name=userName]` does not have a `for="userName"`, which breaks things like `react-testing-library`'s `getByLabelText` and forces me to fallback to less optimal methods for finding and filling inputs, and breaks some browser / a11y behavior.

I have a feeling this is some sort of props issue, but honestly just have not had time to examine further.

(P.S. Thanks for making this!)

**Comment by jannikbuschke** [comment]
That is some cool input. Testing (especially with react-testing-library) and a11y stuff should definitely be fixed. Im not sure how much effort it will be, and it does not necessarily be part of the 1.0 release. Im also fine moving forward to a 2.0 release if it makes sense, or _fix_ things as part of 1.* releases.

**Comment by jannikbuschke** [comment]
accidentally merged. Recreated: #29

**Pull request merged**
