### PR TITLE
Update FormItemProps setting React.children as optional.

### PR DESCRIPTION
**Pull request by jackton1**

### CODE REVIEW

**Comment by jannikbuschke** [comment]
I wonde why FormItem would ever not want to have children? Can you explain your usecase?

**Comment by jackton1** [comment]
Constructing the props passed to the component you'll have to omit the children which should be optional by default are always required which shouldn't be the case.

Also strange the `FormItemProps` requires a name prop which is required by the Input. 

```
const itemProps: Omit<FormItemProps, 'children'> = { name: 'test' };
if (error) {
  itemProps.validateStatus = 'error';
  itemProps.help = (
    <ErrorMessage message={error} onClear={handleFieldReset} />
  );
}
return <Search itemProps={itemProps}></Search>
```

```
interface ISearchProps {
  itemProps?: Omit<FormItemProps, 'children'>;
  selectedChoices?: number[];
}

const Search = ({ itemProps, selectedChoices }: ISearchProps) => {
  return (
    <FormItem {...itemProps}>
       <Select></Select> // React.children
    </FormItem>
  );
}
```

**Comment by jannikbuschke** [comment]
I dont yet fully understand your use case. It seems your FormItem indeed has children, so the type seems fine.

**Comment by jackton1** [comment]
Unable to use Object spread operator without TS2322 ⚠️  warnings.

Screen Shot 2019-10-14 at 10 20 09 AM

**Pull request closed without merging**
