### PR TITLE
SelectField dataSource functionality

### PR DESCRIPTION
**Pull request by jwmann**
Same thing that EnumListEditor does and #11 accomplishes
Backwards compatible and super useful imo

### CODE REVIEW

**Comment by jannikbuschke** [comment]
I am not so happy overall with the DataSource thing, as it doesn't 100% align with antd and it muddles a little with api (if the Antd Select component would get one this would be a different story). Also it doesn't adhere 100% to reacts composability . For example internally we are now rendering a Select.Option with specific values, but the user isn't really in control. For example the style and title properties cannot be injected.

After tinkering a bit I would recommend a solution around these lines:


```
export const SelectField = ({
  name,
  validate,
  children,
  ...restProps
}: FormikFieldProps &
  SelectProps<any> & {
    children?: React.ReactNode;
  }) => {
  return (
    <Field name={name} validate={validate}>
      {({ field: { value, onBlur }, form: { setFieldValue } }: FieldProps) => (
        <Select
          value={value}
          onChange={v => setFieldValue(name, v)}
          onBlur={onBlur}
          {...restProps}
        >
          {children}
        </Select>
      )}
    </Field>
  );
};

type Option = OptionProps & { children: React.ReactNode };

export const renderSelectFieldOptions = (options: Option[]) =>
  options.map((props, index) => <Select.Option key={index} {...props} />);
```
Now the SelectField has the usual formik-antd property convention (name + antd-props). In order to easily allow rendering options without heaving to manually specify a lot of <Select.Option> components I added the renderSelectFieldOptions function. The usage is like this:

```
<SelectField name="select" style={{ width: "100%" }}>
  renderSelectFieldOptions([
 { label: "displayed value", value: 2 },
 { label: <h1>hello world</h1>,  value: "123"  },
 { disabled: true, value: "123", label: "im not enabled"  } ])}
</SelectField>
```
Note: Antds select field expects an array as its children therefore a function return jsx is needed here (I tried wrapping this in its own component which fails, Select expects Select.Option or compatible components as its children)

**Comment by jwmann** [comment]
I can see where you're coming from, and I like the concept of it, I also like that it uses antd's Option type itself as well.
The only thing I don't particularly like about it is the fact that it's another import I'll have to do just to generate the option components.

However I do see what you mean about messing with the API and I don't see any way around that besides doing what you're suggesting.

I don't mind committing the necessary changes to do it the way you're suggesting.

**Comment by jannikbuschke** [comment]
the renderSelectOptions function could also be a static property on the SelectField component. So one less import to do:
`<Select>
  {Select.renderOptions(....)}
</Select>
`

Still a bit more typing, but the benefits outweigh the props approach a lot I think.

Depending on where you come from it might at first look a bit weird or uncommon, at least it did to me. But I am pretty sure its the superior approach (there might be even better ones out there).

I would go for this and then see in practice how it works out. Feel free to apply the changes to this PR (or wait for me doing it in the next days).

**Comment by jwmann** [comment]
>the renderSelectOptions function could also be a static property on the SelectField component. So one less import to do:
`<Select> {Select.renderOptions(....)} </Select>`

I do like this idea a bit better, that way I won't have to do a separate import and doesn't mess with the prop API.
I don't mind setting it up, but I'm not sure to apply a method to a stateless component.
Maybe something like this?

```
export const SelectField = ({
  name,
  validate,
  children,
  ...restProps
}: FormikFieldProps &
  SelectProps<any> & {
    children?: React.ReactNode;
  }) => {
  return (
    <Field name={name} validate={validate}>
      {({ field: { value, onBlur }, form: { setFieldValue } }: FieldProps) => (
        <Select
          value={value}
          onChange={v => setFieldValue(name, v)}
          onBlur={onBlur}
          {...restProps}
        >
          {children}
        </Select>
      )}
    </Field>
  );
};

type Option = OptionProps & { label: React.ReactNode };
SelectField.renderOptions = (options: Option[]) =>
  options.map(({label,...restProps}) => <Select.Option key={index} {...restProps} >{label}</Select.Option>);
```
Does that seem right to you?

**Comment by jannikbuschke** [comment]
Looks good. Pls commit, I will then merge soon.

Im also rethinking my 'options as a prop' aversion. If its possible with typescript to prevent setting both at the same time it could be a practical _addition_. It would allow full control via children composition, but give a practical/simple escape hatch.

**Comment by jwmann** [comment]
> Im also rethinking my 'options as a prop' aversion. If its possible with typescript to prevent setting both at the same time

I'm not sure I follow, could you elaborate?

**Comment by jwmann** [comment]
This new way works really nicely.
```
<SelectField name="select" >
  {SelectField.renderOptions([
    { label: "Foo", value: "foo" },
    { label: <span>Bar</span>, value: "bar" },
    { label: 123, value: 123 },
  ])}
  <Option value="hello">Hello</Option>
  <Option value="world">World</Option>
</SelectField>
```


Once we merge this new method, I think I'll make a PR to change RadioGroupField to adhere to the same method for consistency.

Let me know about your above comment though and I'll make any corrections

**Pull request merged**
